#!/usr/bin/env python3
"""Bootstrap an MFS migration workspace inside a legacy repository.

Usage:
  python tools/mfs_onboard.py --target /path/to/legacy-repo --features billing,search --run-discovery
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path
from string import Template
from typing import Dict, List

ROOT = Path(__file__).resolve().parents[1]
TOOLS_DIR = ROOT / "tools"
BOUNDARY_TEMPLATE = ROOT / "templates" / "boundary" / "boundary.py.tmpl"

PROFILE_PRESETS: Dict[str, Dict[str, object]] = {
    "discovery_only": {
        "features": ["feature-a"],
        "run_discovery": True,
        "discovery_top": 10,
        "notes": "Fast initial triage and candidate surfacing.",
    },
    "planning_pack": {
        "features": ["feature-a", "feature-b"],
        "run_discovery": True,
        "discovery_top": 20,
        "notes": "Balanced discovery and planning workspace for AI-led migration design.",
    },
    "cutover_ready": {
        "features": ["feature-a", "feature-b", "feature-c"],
        "run_discovery": True,
        "discovery_top": 25,
        "notes": "Planning + boundary seeds prepared for cutover workflows.",
    },
    "ci_strict": {
        "features": ["feature-a", "feature-b"],
        "run_discovery": True,
        "discovery_top": 30,
        "notes": "High-signal extraction context intended for stricter CI and gate-driven execution.",
    },
}

SOURCE_EXTENSIONS = {
    ".py",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".go",
    ".java",
    ".kt",
    ".rb",
    ".php",
    ".cs",
    ".rs",
}


def _slugify(raw: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", raw.strip().lower()).strip("-")
    if not slug:
        raise ValueError("Feature name must contain at least one alphanumeric character")
    return slug


def _snake(slug: str) -> str:
    return slug.replace("-", "_")


def _camel(slug: str) -> str:
    return "".join(p.capitalize() for p in slug.split("-"))


def _copy(src: Path, dst: Path, *, force: bool) -> None:
    if dst.exists() and not force:
        return
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def _write_text(path: Path, content: str, *, force: bool) -> None:
    if path.exists() and not force:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _render_boundary(feature_slug: str, port: int) -> str:
    tpl = Template(BOUNDARY_TEMPLATE.read_text(encoding="utf-8"))
    feature_snake = _snake(feature_slug)
    class_name = f"{_camel(feature_slug)}Boundary"
    return tpl.substitute(
        {
            "feature_slug": feature_slug,
            "class_name": class_name,
            "env_prefix": f"MFS_{feature_snake.upper()}",
            "default_base_url": f"http://localhost:{port}",
            "source_name": f"{feature_snake}_boundary",
            "capabilities_path": f"/v1/{feature_slug}/capabilities",
            "call_path": f"/v1/{feature_slug}",
            "call_method": "POST",
            "factory_name": f"get_{feature_snake}_boundary",
        }
    )


def _plan_skeleton(features: List[str]) -> str:
    lines = [
        "# MFS Migration Plan Skeleton",
        "",
        "## Context",
        "- Legacy app:",
        "- Owner:",
        "- Environment:",
        "",
        "## Candidate Waves",
    ]
    for idx, feat in enumerate(features or ["feature-a", "feature-b"], start=1):
        lines.extend(
            [
                f"### Wave {idx}: {feat}",
                "- Why this feature:",
                "- Contract endpoint:",
                "- Boundary adapter path:",
                "- UI parity risks:",
                "- Rollback trigger:",
                "",
            ]
        )
    lines.extend(
        [
            "## Execution Checklist",
            "- [ ] Run candidate discovery",
            "- [ ] Merge runtime signals",
            "- [ ] Finalize scoring and wave order",
            "- [ ] Scaffold service + boundary",
            "- [ ] Prepare cutover manifest",
            "- [ ] Run UI parity checklist + smoke",
            "- [ ] Promote canary",
            "- [ ] Validate and expand rollout",
            "",
        ]
    )
    return "\n".join(lines)


def _workspace_readme(workspace: Path, features: List[str], mfs_root: Path) -> str:
    features_text = ", ".join(features) if features else "(add feature names)"
    return "\n".join(
        [
            "# MFS Onboarding Workspace",
            "",
            f"This workspace was generated by MFS at `{mfs_root}`.",
            "",
            "## Included",
            "- `migration_intake.md`",
            "- `candidate_scores.csv`",
            "- `runtime_signals.csv`",
            "- `migration_plan.md`",
            "- `boundaries/*.py`",
            "- `AI_DEV_START.md`",
            "- `context_manifest.json`",
            "- `run_mfs_sequence.ps1`",
            "",
            "## Suggested Flow",
            "1. Read `AI_DEV_START.md` first.",
            "2. Fill `migration_intake.md`.",
            "3. Run `run_mfs_sequence.ps1` (or commands manually).",
            "4. Customize generated boundary stubs and connect to host app.",
            "5. Create cutover manifests and run parity/cutover gates.",
            "",
            f"## Seed Features\n{features_text}",
            "",
            f"Workspace root: `{workspace}`",
        ]
    )


def _ai_dev_start(
    mfs_root: Path,
    workspace: Path,
    target: Path,
    profile: str,
    profile_notes: str,
    discovery_top: int,
) -> str:
    return "\n".join(
        [
            "# AI Dev Start Guide",
            "",
            "## Objective",
            "Use MFS to migrate large/high-risk legacy features into containerized services while preserving existing UI behavior.",
            "",
            "## Onboarding Profile",
            f"- Profile: `{profile}`",
            f"- Notes: {profile_notes}",
            "",
            "## Read First (MFS Docs)",
            f"- `{mfs_root / 'README.md'}`",
            f"- `{mfs_root / 'docs/MFS_FRAMEWORK_REFERENCE.md'}`",
            f"- `{mfs_root / 'docs/MIGRATION_PLAYBOOK.md'}`",
            f"- `{mfs_root / 'docs/BOUNDARY_SDK.md'}`",
            f"- `{mfs_root / 'docs/CUTOVER_ORCHESTRATION.md'}`",
            f"- `{mfs_root / 'docs/UI_PARITY_HARNESS.md'}`",
            "",
            "## Workspace Inputs",
            f"- `{workspace / 'migration_intake.md'}`",
            f"- `{workspace / 'candidate_scores.csv'}`",
            f"- `{workspace / 'runtime_signals.csv'}`",
            f"- `{workspace / 'migration_plan.md'}`",
            f"- `{workspace / 'boundaries'}`",
            "",
            "## Recommended Command Sequence",
            f"1. `python {mfs_root / 'tools/discover_candidates.py'} --target {target} --output-dir {workspace / 'discovery'} --top {max(1, discovery_top)} --exclude-buckets docs,tools,scripts,tests,infra`",
            f"2. `python {mfs_root / 'tools/merge_candidate_signals.py'} --candidates {workspace / 'discovery/candidate_scores.csv'} --runtime {workspace / 'runtime_signals.csv'} --output {workspace / 'discovery/merged_candidate_scores.csv'}`",
            f"3. `python {mfs_root / 'tools/score_candidates.py'} --input {workspace / 'discovery/merged_candidate_scores.csv'} --top {max(1, discovery_top)} --output-json {workspace / 'discovery/score_results.json'}`",
            "",
            "## Expected Outputs",
            f"- `{workspace / 'discovery/migration_report.md'}`",
            f"- `{workspace / 'discovery/merged_candidate_scores.csv'}`",
            f"- `{workspace / 'discovery/score_results.json'}`",
            "",
            "Use those outputs to finalize candidate waves in `migration_plan.md` and then scaffold services/boundaries.",
        ]
    )


def _run_script(path_args: List[str], cwd: Path) -> int:
    proc = subprocess.run(path_args, cwd=str(cwd), check=False)
    return int(proc.returncode)


def _infer_profile(target: Path) -> tuple[str, str]:
    source_files = 0
    route_like = 0
    test_like = 0
    dominant_ext: Dict[str, int] = {}

    for path in target.rglob("*"):
        if not path.is_file():
            continue
        if any(part in {".git", "node_modules", "dist", "build", "__pycache__", ".venv", "venv"} for part in path.parts):
            continue
        suffix = path.suffix.lower()
        if suffix not in SOURCE_EXTENSIONS:
            continue
        source_files += 1
        dominant_ext[suffix] = dominant_ext.get(suffix, 0) + 1
        rel = str(path).lower()
        if any(token in rel for token in ["test", "spec", "__tests__"]):
            test_like += 1
        if any(token in rel for token in ["route", "controller", "handler", "api"]):
            route_like += 1
        if source_files >= 12000:
            break

    test_ratio = (test_like / source_files) if source_files else 0.0
    route_ratio = (route_like / source_files) if source_files else 0.0
    stack = max(dominant_ext.items(), key=lambda kv: kv[1])[0] if dominant_ext else "unknown"

    if source_files < 300 and route_ratio < 0.03:
        return (
            "discovery_only",
            f"auto-selected discovery_only (files={source_files}, route_ratio={route_ratio:.3f}, stack={stack})",
        )
    if source_files > 3000 or route_ratio > 0.12:
        return (
            "ci_strict",
            f"auto-selected ci_strict (files={source_files}, route_ratio={route_ratio:.3f}, stack={stack})",
        )
    if test_ratio > 0.2 and route_ratio > 0.05:
        return (
            "cutover_ready",
            f"auto-selected cutover_ready (files={source_files}, test_ratio={test_ratio:.3f}, route_ratio={route_ratio:.3f}, stack={stack})",
        )
    return (
        "planning_pack",
        f"auto-selected planning_pack (files={source_files}, test_ratio={test_ratio:.3f}, route_ratio={route_ratio:.3f}, stack={stack})",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Create MFS onboarding workspace in a legacy repo")
    parser.add_argument("--target", required=True, help="Path to legacy repository root")
    parser.add_argument("--workspace", default="mfs_migration", help="Workspace directory name under target")
    parser.add_argument(
        "--profile",
        default="planning_pack",
        choices=sorted([*PROFILE_PRESETS.keys(), "auto"]),
        help="Named onboarding task profile",
    )
    parser.add_argument("--features", default="", help="Comma-separated feature names for boundary stubs")
    parser.add_argument("--run-discovery", action="store_true", help="Run discover_candidates immediately into workspace/discovery")
    parser.add_argument("--discovery-top", type=int, default=None, help="Top candidates to print during discovery")
    parser.add_argument("--force", action="store_true", help="Overwrite generated files if present")
    args = parser.parse_args()

    target = Path(args.target).resolve()
    if not target.exists() or not target.is_dir():
        raise FileNotFoundError(f"Target must be an existing directory: {target}")

    workspace = target / args.workspace
    workspace.mkdir(parents=True, exist_ok=True)

    auto_notes = ""
    if args.profile == "auto":
        inferred, auto_notes = _infer_profile(target)
        args.profile = inferred
    profile_cfg = PROFILE_PRESETS.get(args.profile, PROFILE_PRESETS["planning_pack"])

    features = [_slugify(x) for x in args.features.split(",") if x.strip()]
    if not features:
        features = [str(x) for x in profile_cfg.get("features", ["feature-a", "feature-b"])]

    if not args.run_discovery and bool(profile_cfg.get("run_discovery", False)):
        args.run_discovery = True
    if args.discovery_top is None:
        try:
            args.discovery_top = int(profile_cfg.get("discovery_top", 20))
        except (TypeError, ValueError):
            args.discovery_top = 20

    _copy(TOOLS_DIR / "migration_intake.md", workspace / "migration_intake.md", force=args.force)
    _copy(TOOLS_DIR / "candidate_scores_template.csv", workspace / "candidate_scores.csv", force=args.force)
    _copy(TOOLS_DIR / "runtime_signals_template.csv", workspace / "runtime_signals.csv", force=args.force)
    _copy(TOOLS_DIR / "ui_parity_checklist_template.json", workspace / "ui_parity_checklist.json", force=args.force)
    _copy(TOOLS_DIR / "ui_smoke_spec_template.json", workspace / "ui_smoke_spec.json", force=args.force)

    _write_text(workspace / "migration_plan.md", _plan_skeleton(features), force=args.force)
    _write_text(workspace / "README.md", _workspace_readme(workspace, features, ROOT), force=args.force)
    _write_text(
        workspace / "AI_DEV_START.md",
        _ai_dev_start(
            ROOT,
            workspace,
            target,
            args.profile,
            f"{str(profile_cfg.get('notes', ''))} {auto_notes}".strip(),
            int(args.discovery_top),
        ),
        force=args.force,
    )

    boundaries_dir = workspace / "boundaries"
    base_port = 8700
    for idx, feature in enumerate(features):
        boundary_file = boundaries_dir / f"{_snake(feature)}_boundary.py"
        _write_text(boundary_file, _render_boundary(feature, base_port + idx), force=args.force)

    discovery_dir = workspace / "discovery"
    commands_ps1 = "\n".join(
        [
            f"python \"{ROOT / 'tools/discover_candidates.py'}\" --target \"{target}\" --output-dir \"{discovery_dir}\" --top {max(1, args.discovery_top)} --exclude-buckets docs,tools,scripts,tests,infra",
            f"python \"{ROOT / 'tools/merge_candidate_signals.py'}\" --candidates \"{discovery_dir / 'candidate_scores.csv'}\" --runtime \"{workspace / 'runtime_signals.csv'}\" --output \"{discovery_dir / 'merged_candidate_scores.csv'}\"",
            f"python \"{ROOT / 'tools/score_candidates.py'}\" --input \"{discovery_dir / 'merged_candidate_scores.csv'}\" --top {max(1, args.discovery_top)} --output-json \"{discovery_dir / 'score_results.json'}\"",
        ]
    )
    _write_text(workspace / "run_mfs_sequence.ps1", commands_ps1 + "\n", force=args.force)

    context_manifest: Dict[str, object] = {
        "mfs_root": str(ROOT),
        "legacy_target": str(target),
        "workspace": str(workspace),
        "profile": args.profile,
        "profile_notes": f"{str(profile_cfg.get('notes', ''))} {auto_notes}".strip(),
        "docs": {
            "readme": str(ROOT / "README.md"),
            "framework_reference": str(ROOT / "docs/MFS_FRAMEWORK_REFERENCE.md"),
            "migration_playbook": str(ROOT / "docs/MIGRATION_PLAYBOOK.md"),
            "boundary_sdk": str(ROOT / "docs/BOUNDARY_SDK.md"),
            "cutover": str(ROOT / "docs/CUTOVER_ORCHESTRATION.md"),
            "ui_parity": str(ROOT / "docs/UI_PARITY_HARNESS.md"),
        },
        "workspace_files": {
            "intake": str(workspace / "migration_intake.md"),
            "candidate_csv": str(workspace / "candidate_scores.csv"),
            "runtime_csv": str(workspace / "runtime_signals.csv"),
            "plan": str(workspace / "migration_plan.md"),
            "boundaries_dir": str(workspace / "boundaries"),
            "ai_start": str(workspace / "AI_DEV_START.md"),
            "sequence_script": str(workspace / "run_mfs_sequence.ps1"),
        },
        "features": features,
        "discovery_dir": str(discovery_dir),
    }
    (workspace / "context_manifest.json").write_text(json.dumps(context_manifest, indent=2), encoding="utf-8")

    if args.run_discovery:
        discovery_dir.mkdir(parents=True, exist_ok=True)
        rc = _run_script(
            [
                sys.executable,
                str(ROOT / "tools/discover_candidates.py"),
                "--target",
                str(target),
                "--output-dir",
                str(discovery_dir),
                "--top",
                str(max(1, args.discovery_top)),
                "--exclude-buckets",
                "docs,tools,scripts,tests,infra",
            ],
            cwd=ROOT,
        )
        if rc != 0:
            print("warning: discovery run failed during onboarding; workspace still generated")

    print(f"Created onboarding workspace: {workspace}")
    print(f"Profile: {args.profile}")
    print("Files:")
    print(f"- {workspace / 'AI_DEV_START.md'}")
    print(f"- {workspace / 'context_manifest.json'}")
    print(f"- {workspace / 'migration_intake.md'}")
    print(f"- {workspace / 'candidate_scores.csv'}")
    print(f"- {workspace / 'runtime_signals.csv'}")
    print(f"- {workspace / 'migration_plan.md'}")
    print(f"- {workspace / 'run_mfs_sequence.ps1'}")
    print(f"- {workspace / 'boundaries'}")
    if args.run_discovery:
        print(f"- {discovery_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
