#!/usr/bin/env python3
"""Semantic Parity Harness
Evaluates parity.jsonl generated by the boundary SDK shadow mode.
"""

import argparse
import json
import os
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List

def _get_criticality(path: str, method: str) -> str:
    path_lower = path.lower()
    if any(k in path_lower for k in ["auth", "payment", "permission", "security", "login", "role", "billing"]):
        return "critical"
    if method.upper() in ["POST", "PUT", "PATCH", "DELETE"]:
        return "write"
    if any(k in path_lower for k in ["sensitive", "user", "profile", "account"]):
        return "read_sensitive"
    if method.upper() == "GET":
        return "read_nonsensitive"
    return "unknown"

def _get_threshold(criticality: str) -> float:
    return {
        "critical": 1.00,
        "write": 0.99,
        "read_sensitive": 0.98,
        "read_nonsensitive": 0.95,
        "unknown": 0.99
    }.get(criticality, 0.99)

def main() -> int:
    parser = argparse.ArgumentParser(description="Evaluate semantic parity logs")
    parser.add_argument("--log-file", required=True, help="Path to parity.jsonl")
    parser.add_argument("--output", required=True, help="Path to write parity summary json")
    parser.add_argument("--min-samples", type=int, default=25, help="Minimum required sample count")
    args = parser.parse_args()

    log_file = Path(args.log_file).resolve()
    output_file = Path(args.output).resolve()

    if not log_file.exists() or not log_file.is_file():
        print(f"Error: Parity log not found at {log_file}")
        sys.exit(1)

    samples = []
    try:
        with log_file.open("r", encoding="utf-8") as f:
            for line in f:
                if not line.strip():
                    continue
                try:
                    samples.append(json.loads(line))
                except json.JSONDecodeError:
                    pass
    except Exception as e:
        print(f"Error reading parity log: {e}")
        sys.exit(1)

    total_samples = len(samples)
    if total_samples == 0:
        print("Error: Empty parity log.")
        sys.exit(1)

    endpoints = defaultdict(lambda: {"matches": 0, "total": 0, "mismatched_keys": set()})
    global_matches = 0

    for s in samples:
        path = s.get("path", "")
        method = s.get("method", "")
        match = s.get("match", False)
        keys = s.get("mismatched_keys", [])
        
        ep_key = f"{method} {path}"
        endpoints[ep_key]["total"] += 1
        if match:
            endpoints[ep_key]["matches"] += 1
            global_matches += 1
        else:
            endpoints[ep_key]["mismatched_keys"].update(keys)

    global_rate = global_matches / total_samples

    report = {
        "status": "PASS",
        "reason": "All parity thresholds met",
        "total_samples": total_samples,
        "global_match_rate": global_rate,
        "endpoints": {}
    }

    if total_samples < args.min_samples:
        report["status"] = "FAIL"
        report["reason"] = f"Sample count {total_samples} is below minimum {args.min_samples}"

    critical_mismatches = []
    for ep, data in endpoints.items():
        parts = ep.split(" ", 1)
        method = parts[0] if len(parts) > 1 else ""
        path = parts[1] if len(parts) > 1 else ep
        
        criticality = _get_criticality(path, method)
        threshold = _get_threshold(criticality)
        rate = data["matches"] / data["total"] if data["total"] > 0 else 0
        
        ep_report = {
            "criticality": criticality,
            "threshold": threshold,
            "match_rate": rate,
            "total": data["total"],
            "mismatched_keys": list(data["mismatched_keys"]),
            "pass": rate >= threshold
        }
        report["endpoints"][ep] = ep_report
        
        if not ep_report["pass"]:
            report["status"] = "FAIL"
            critical_mismatches.append(ep)

    if critical_mismatches and report["status"] != "FAIL":
        report["status"] = "FAIL"
    
    if report["status"] == "FAIL" and report["reason"] == "All parity thresholds met":
        report["reason"] = f"Failed parity threshold on endpoints: {', '.join(critical_mismatches)}"

    output_file.parent.mkdir(parents=True, exist_ok=True)
    with output_file.open("w", encoding="utf-8") as f:
        json.dump(report, f, indent=2)

    print(json.dumps(report, indent=2))
    return 0 if report["status"] == "PASS" else 1

if __name__ == "__main__":
    sys.exit(main())
